# Generated by Django 6.0 on 2025-12-27 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='Account',
        ),
    ]
